#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
	
	
	/// <summary>
	/// Стан сутності "Car"
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.149")]
	public enum uds_car_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Опис стану сутності "Car"
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.149")]
	public enum uds_car_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.149")]
	public enum uds_car_uds_carmanufacturer
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnknownLabel0 = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnknownLabel1 = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnknownLabel2 = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnknownLabel3 = 3,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("uds_car")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.149")]
	public partial class uds_car : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public uds_car() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "uds_car";
		
		public const string EntityLogicalCollectionName = "uds_cars";
		
		public const string EntitySetName = "uds_cars";
		
		public const int EntityTypeCode = 10780;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Унікальний ідентифікатор користувача, який створив запис.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Дата та час створення запису.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Унікальний ідентифікатор користувача-представника, який створив запис.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Порядковий номер імпорту, під час якого було створено цей запис.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Унікальний ідентифікатор користувача, який змінив запис.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Дата та час змінення запису.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Унікальний ідентифікатор користувача-представника, який змінив запис.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Дата та час перенесення запису.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Ідентифікатор відповідального
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Унікальний ідентифікатор підрозділу, який відповідає за запис
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Унікальний ідентифікатор робочої групи, яка відповідає за запис.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Унікальний ідентифікатор користувача, який відповідає за запис.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Стан сутності "Car"
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual uds_car_statecode? statecode
		{
			get
			{
				return ((uds_car_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.OnPropertyChanging("statecode");
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statecode");
			}
		}
		
		/// <summary>
		/// Опис стану сутності "Car"
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual uds_car_statuscode? statuscode
		{
			get
			{
				return ((uds_car_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statuscode");
			}
		}
		
		/// <summary>
		/// Лише для внутрішнього використання.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uds_car")]
		public Microsoft.Xrm.Sdk.EntityReference uds_car1
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("uds_car");
			}
			set
			{
				this.OnPropertyChanging("uds_car1");
				this.SetAttributeValue("uds_car", value);
				this.OnPropertyChanged("uds_car1");
			}
		}
		
		/// <summary>
		/// Унікальний ідентифікатор одного з екземплярів сутності
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uds_carid")]
		public System.Nullable<System.Guid> uds_carId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("uds_carid");
			}
			set
			{
				this.OnPropertyChanging("uds_carId");
				this.SetAttributeValue("uds_carid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("uds_carId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uds_carid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.uds_carId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uds_carmanufacturer")]
		public virtual uds_car_uds_carmanufacturer? uds_Carmanufacturer
		{
			get
			{
				return ((uds_car_uds_carmanufacturer?)(EntityOptionSetEnum.GetEnum(this, "uds_carmanufacturer")));
			}
			set
			{
				this.OnPropertyChanging("uds_Carmanufacturer");
				this.SetAttributeValue("uds_carmanufacturer", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("uds_Carmanufacturer");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uds_carmodel")]
		public string uds_carmodel
		{
			get
			{
				return this.GetAttributeValue<string>("uds_carmodel");
			}
			set
			{
				this.OnPropertyChanging("uds_carmodel");
				this.SetAttributeValue("uds_carmodel", value);
				this.OnPropertyChanged("uds_carmodel");
			}
		}
		
		/// <summary>
		/// Назва настроюваної сутності.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uds_name")]
		public string uds_name
		{
			get
			{
				return this.GetAttributeValue<string>("uds_name");
			}
			set
			{
				this.OnPropertyChanging("uds_name");
				this.SetAttributeValue("uds_name", value);
				this.OnPropertyChanged("uds_name");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uds_production")]
		public System.Nullable<System.DateTime> uds_production
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("uds_production");
			}
			set
			{
				this.OnPropertyChanging("uds_production");
				this.SetAttributeValue("uds_production", value);
				this.OnPropertyChanged("uds_production");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uds_purchase")]
		public System.Nullable<System.DateTime> uds_purchase
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("uds_purchase");
			}
			set
			{
				this.OnPropertyChanging("uds_purchase");
				this.SetAttributeValue("uds_purchase", value);
				this.OnPropertyChanged("uds_purchase");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uds_vinnumber")]
		public string uds_VINnumber
		{
			get
			{
				return this.GetAttributeValue<string>("uds_vinnumber");
			}
			set
			{
				this.OnPropertyChanging("uds_VINnumber");
				this.SetAttributeValue("uds_vinnumber", value);
				this.OnPropertyChanged("uds_VINnumber");
			}
		}
		
		/// <summary>
		/// Код часового поясу, використаний під час створення запису.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Номер версії
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
	}
	
	
}
#pragma warning restore CS1591
