#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Entities
{
	
	
	/// <summary>
	/// Стан сутності "Rent"
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.149")]
	public enum uds_rent_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Опис стану сутності "Rent"
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.149")]
	public enum uds_rent_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.149")]
	public enum uds_rent_uds_pickup_location
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnknownLabel0 = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnknownLabel1 = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnknownLabel2 = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.149")]
	public enum uds_rent_uds_return_location
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnknownLabel0 = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnknownLabel1 = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnknownLabel2 = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("uds_rent")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.149")]
	public partial class uds_rent : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public uds_rent() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "uds_rent";
		
		public const string EntityLogicalCollectionName = "uds_rents";
		
		public const string EntitySetName = "uds_rents";
		
		public const int EntityTypeCode = 10781;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Унікальний ідентифікатор користувача, який створив запис.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Дата та час створення запису.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Унікальний ідентифікатор користувача-представника, який створив запис.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Обмінний курс, пов’язаний із сутністю, відносно базової грошової одиниці.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// Порядковий номер імпорту, під час якого було створено цей запис.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Унікальний ідентифікатор користувача, який змінив запис.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Дата та час змінення запису.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Унікальний ідентифікатор користувача-представника, який змінив запис.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Дата та час перенесення запису.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Ідентифікатор відповідального
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Унікальний ідентифікатор підрозділу, який відповідає за запис
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Унікальний ідентифікатор робочої групи, яка відповідає за запис.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Унікальний ідентифікатор користувача, який відповідає за запис.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Стан сутності "Rent"
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual uds_rent_statecode? statecode
		{
			get
			{
				return ((uds_rent_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.OnPropertyChanging("statecode");
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statecode");
			}
		}
		
		/// <summary>
		/// Опис стану сутності "Rent"
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual uds_rent_statuscode? statuscode
		{
			get
			{
				return ((uds_rent_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statuscode");
			}
		}
		
		/// <summary>
		/// Лише для внутрішнього використання.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Унікальний ідентифікатор грошової одиниці, пов’язаної із сутністю.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			set
			{
				this.OnPropertyChanging("TransactionCurrencyId");
				this.SetAttributeValue("transactioncurrencyid", value);
				this.OnPropertyChanged("TransactionCurrencyId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uds_actual_pickup")]
		public System.Nullable<System.DateTime> uds_actual_pickup
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("uds_actual_pickup");
			}
			set
			{
				this.OnPropertyChanging("uds_actual_pickup");
				this.SetAttributeValue("uds_actual_pickup", value);
				this.OnPropertyChanged("uds_actual_pickup");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uds_actual_return")]
		public System.Nullable<System.DateTime> uds_actual_return
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("uds_actual_return");
			}
			set
			{
				this.OnPropertyChanging("uds_actual_return");
				this.SetAttributeValue("uds_actual_return", value);
				this.OnPropertyChanged("uds_actual_return");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uds_car")]
		public Microsoft.Xrm.Sdk.EntityReference uds_car
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("uds_car");
			}
			set
			{
				this.OnPropertyChanging("uds_car");
				this.SetAttributeValue("uds_car", value);
				this.OnPropertyChanged("uds_car");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uds_carclass")]
		public Microsoft.Xrm.Sdk.EntityReference uds_carclass
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("uds_carclass");
			}
			set
			{
				this.OnPropertyChanging("uds_carclass");
				this.SetAttributeValue("uds_carclass", value);
				this.OnPropertyChanged("uds_carclass");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uds_customer")]
		public Microsoft.Xrm.Sdk.EntityReference uds_customer
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("uds_customer");
			}
			set
			{
				this.OnPropertyChanging("uds_customer");
				this.SetAttributeValue("uds_customer", value);
				this.OnPropertyChanged("uds_customer");
			}
		}
		
		/// <summary>
		/// Назва настроюваної сутності.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uds_name")]
		public string uds_name
		{
			get
			{
				return this.GetAttributeValue<string>("uds_name");
			}
			set
			{
				this.OnPropertyChanging("uds_name");
				this.SetAttributeValue("uds_name", value);
				this.OnPropertyChanged("uds_name");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uds_paid")]
		public System.Nullable<bool> uds_paid
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("uds_paid");
			}
			set
			{
				this.OnPropertyChanging("uds_paid");
				this.SetAttributeValue("uds_paid", value);
				this.OnPropertyChanged("uds_paid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uds_pickup_location")]
		public virtual uds_rent_uds_pickup_location? uds_pickup_location
		{
			get
			{
				return ((uds_rent_uds_pickup_location?)(EntityOptionSetEnum.GetEnum(this, "uds_pickup_location")));
			}
			set
			{
				this.OnPropertyChanging("uds_pickup_location");
				this.SetAttributeValue("uds_pickup_location", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("uds_pickup_location");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uds_pickupreport")]
		public Microsoft.Xrm.Sdk.EntityReference uds_Pickupreport
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("uds_pickupreport");
			}
			set
			{
				this.OnPropertyChanging("uds_Pickupreport");
				this.SetAttributeValue("uds_pickupreport", value);
				this.OnPropertyChanged("uds_Pickupreport");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uds_price")]
		public Microsoft.Xrm.Sdk.Money uds_price
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("uds_price");
			}
			set
			{
				this.OnPropertyChanging("uds_price");
				this.SetAttributeValue("uds_price", value);
				this.OnPropertyChanged("uds_price");
			}
		}
		
		/// <summary>
		/// Значення поля "Price" в базових грошових одиницях.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uds_price_base")]
		public Microsoft.Xrm.Sdk.Money uds_price_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("uds_price_base");
			}
		}
		
		/// <summary>
		/// Унікальний ідентифікатор одного з екземплярів сутності
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uds_rentid")]
		public System.Nullable<System.Guid> uds_rentId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("uds_rentid");
			}
			set
			{
				this.OnPropertyChanging("uds_rentId");
				this.SetAttributeValue("uds_rentid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("uds_rentId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uds_rentid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.uds_rentId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uds_reserved_handover")]
		public System.Nullable<System.DateTime> uds_reserved_handover
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("uds_reserved_handover");
			}
			set
			{
				this.OnPropertyChanging("uds_reserved_handover");
				this.SetAttributeValue("uds_reserved_handover", value);
				this.OnPropertyChanged("uds_reserved_handover");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uds_reserved_pickup")]
		public System.Nullable<System.DateTime> uds_reserved_pickup
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("uds_reserved_pickup");
			}
			set
			{
				this.OnPropertyChanging("uds_reserved_pickup");
				this.SetAttributeValue("uds_reserved_pickup", value);
				this.OnPropertyChanged("uds_reserved_pickup");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uds_return_location")]
		public virtual uds_rent_uds_return_location? uds_return_location
		{
			get
			{
				return ((uds_rent_uds_return_location?)(EntityOptionSetEnum.GetEnum(this, "uds_return_location")));
			}
			set
			{
				this.OnPropertyChanging("uds_return_location");
				this.SetAttributeValue("uds_return_location", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("uds_return_location");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uds_returnreport")]
		public Microsoft.Xrm.Sdk.EntityReference uds_Returnreport
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("uds_returnreport");
			}
			set
			{
				this.OnPropertyChanging("uds_Returnreport");
				this.SetAttributeValue("uds_returnreport", value);
				this.OnPropertyChanged("uds_Returnreport");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uds_status")]
		public Microsoft.Xrm.Sdk.EntityReference uds_Status
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("uds_status");
			}
			set
			{
				this.OnPropertyChanging("uds_Status");
				this.SetAttributeValue("uds_status", value);
				this.OnPropertyChanged("uds_Status");
			}
		}
		
		/// <summary>
		/// Код часового поясу, використаний під час створення запису.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Номер версії
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
	}
	
}
#pragma warning restore CS1591
