#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Entities
{
	
	
	/// <summary>
	/// Стан сутності "Car transfer report"
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.149")]
	public enum uds_car_transfer_report_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Опис стану сутності "Car transfer report"
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.149")]
	public enum uds_car_transfer_report_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("uds_car_transfer_report")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.149")]
	public partial class uds_car_transfer_report : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public uds_car_transfer_report() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "uds_car_transfer_report";
		
		public const string EntityLogicalCollectionName = "uds_car_transfer_reports";
		
		public const string EntitySetName = "uds_car_transfer_reports";
		
		public const int EntityTypeCode = 10783;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Унікальний ідентифікатор користувача, який створив запис.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Дата та час створення запису.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Унікальний ідентифікатор користувача-представника, який створив запис.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Порядковий номер імпорту, під час якого було створено цей запис.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Унікальний ідентифікатор користувача, який змінив запис.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Дата та час змінення запису.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Унікальний ідентифікатор користувача-представника, який змінив запис.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Дата та час перенесення запису.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Ідентифікатор відповідального
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Унікальний ідентифікатор підрозділу, який відповідає за запис
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Унікальний ідентифікатор робочої групи, яка відповідає за запис.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Унікальний ідентифікатор користувача, який відповідає за запис.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Стан сутності "Car transfer report"
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual uds_car_transfer_report_statecode? statecode
		{
			get
			{
				return ((uds_car_transfer_report_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.OnPropertyChanging("statecode");
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statecode");
			}
		}
		
		/// <summary>
		/// Опис стану сутності "Car transfer report"
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual uds_car_transfer_report_statuscode? statuscode
		{
			get
			{
				return ((uds_car_transfer_report_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statuscode");
			}
		}
		
		/// <summary>
		/// Лише для внутрішнього використання.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uds_car")]
		public Microsoft.Xrm.Sdk.EntityReference uds_car
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("uds_car");
			}
			set
			{
				this.OnPropertyChanging("uds_car");
				this.SetAttributeValue("uds_car", value);
				this.OnPropertyChanged("uds_car");
			}
		}
		
		/// <summary>
		/// Унікальний ідентифікатор одного з екземплярів сутності
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uds_car_transfer_reportid")]
		public System.Nullable<System.Guid> uds_car_transfer_reportId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("uds_car_transfer_reportid");
			}
			set
			{
				this.OnPropertyChanging("uds_car_transfer_reportId");
				this.SetAttributeValue("uds_car_transfer_reportid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("uds_car_transfer_reportId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uds_car_transfer_reportid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.uds_car_transfer_reportId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uds_damage_description")]
		public string uds_damage_description
		{
			get
			{
				return this.GetAttributeValue<string>("uds_damage_description");
			}
			set
			{
				this.OnPropertyChanging("uds_damage_description");
				this.SetAttributeValue("uds_damage_description", value);
				this.OnPropertyChanged("uds_damage_description");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uds_damages")]
		public System.Nullable<bool> uds_damages
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("uds_damages");
			}
			set
			{
				this.OnPropertyChanging("uds_damages");
				this.SetAttributeValue("uds_damages", value);
				this.OnPropertyChanged("uds_damages");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uds_date")]
		public System.Nullable<System.DateTime> uds_date
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("uds_date");
			}
			set
			{
				this.OnPropertyChanging("uds_date");
				this.SetAttributeValue("uds_date", value);
				this.OnPropertyChanged("uds_date");
			}
		}
		
		/// <summary>
		/// Назва настроюваної сутності.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uds_name")]
		public string uds_name
		{
			get
			{
				return this.GetAttributeValue<string>("uds_name");
			}
			set
			{
				this.OnPropertyChanging("uds_name");
				this.SetAttributeValue("uds_name", value);
				this.OnPropertyChanged("uds_name");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uds_type")]
		public System.Nullable<bool> uds_type
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("uds_type");
			}
			set
			{
				this.OnPropertyChanging("uds_type");
				this.SetAttributeValue("uds_type", value);
				this.OnPropertyChanged("uds_type");
			}
		}
		
		/// <summary>
		/// Код часового поясу, використаний під час створення запису.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Номер версії
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
	}
	
	
	
}
#pragma warning restore CS1591
